# Generated by Django 6.0.3 on 2026-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_price_sats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
