# Generated by Django 6.0.3 on 2026-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('price_a_sats', models.IntegerField()),
                ('price_b_sats', models.IntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('winner_idx', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ['-created_at'],
            },
        ),
    ]
