# Generated by Django 6.0.3 on 2026-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='votes_a',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='market',
            name='votes_b',
            field=models.IntegerField(default=1),
        ),
    ]
